services:
  app:
    image: ghcr.io/rodolfofigueroa/fanzadl-webui:latest
    container_name: fanzadl-webui
    ports:
      - "4352:4352"
    env_file:
      - .env
    volumes:
      - ${DOWNLOAD_DIR}:/download
      - image_cache:/image_cache
      - token_data:/data
    restart: unless-stopped

volumes:
  image_cache:
  token_data:
