services:
  app:
    image: ghcr.io/rodolfofigueroa/fanzadl-webui:latest
    container_name: fanzadl-webui
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - <YOUR_DOWNLOAD_DIR>:/download
      - image_cache:/image_cache
    restart: unless-stopped

volumes:
  image_cache:
