services:
  app:
    image: fanzadl-webui:latest
    container_name: fanzadl-webui-dev
    build: .
    ports:
      - "4352:4352"
    env_file:
      - .env
    volumes:
      - downloads:/download
      - image_cache:/image_cache
    restart: unless-stopped

volumes:
  downloads:
  image_cache:
