services:
  app:
    image: fanzadl-webui:latest
    container_name: fanzadl-webui
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - downloads:/download
      - image_cache:/image_cache
    restart: unless-stopped

volumes:
  downloads:
  image_cache:
